CREATE TABLE "GCG_6325_SYS_AUDIT" (
 "IDENTIFIER" CHAR(30),
 "FIELD_NAME" CHAR(50),
 "OLD_VALUE" LONGVARCHAR,
 "NEW_VALUE" LONGVARCHAR,
 "CHG_PGM" CHAR(8),
 "SCREEN" CHAR(20),
 "MENU_REF" LONGVARCHAR,
 "CHG_USER" CHAR(8),
 "CHG_DATE" DATE,
 "CHG_TIME" TIME );
CREATE INDEX "GCG_6325_IDX1" USING 0 ON "GCG_6325_SYS_AUDIT" ( "IDENTIFIER" );
