CREATE TABLE "GCG_6325_AUDIT_MX" (
 "REC_ID" CHAR(1),
 "CUST_MASTER" BIT NOT NULL,
 "VEND_MASTER" BIT NOT NULL,
 "PART_MASTER" BIT NOT NULL,
 "USER_SEC_MX" BIT NOT NULL,
 "GROUP_SEC_MX" BIT NOT NULL );